---
title: "Astronaut data"
author: "Nathan"
date: "29/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Read in dataset and add in new column for mission age.

Set nationality and mission_number as factors for later graph. Redefine nationality to US, Russia or Other to reduce options given the distribution.
```{r}
astronauts <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-14/astronauts.csv')

astronauts %>% count(nationality, sort=TRUE)

astronauts_2 <- astronauts %>%  mutate(mission_age=year_of_mission-year_of_birth, nationality=as.factor(case_when(nationality=="U.S." ~ "US", str_detect(nationality,"Russia")~"Russia", TRUE ~ "Other")), mission_number=as.factor(mission_number))

```


```{r, dpi=200, fig.asp=1}
library(RColorBrewer)

astronauts_2$nationality<-factor(astronauts_2$nationality, levels(astronauts_2$nationality)[c(3:1)])  #reorder nationality in reverse order

astronauts_2 %>% ggplot(aes(x=year_of_mission, y=mission_age, color=mission_number, size= hours_mission))+
  geom_point(alpha=0.5, aes(shape=nationality))+
  facet_wrap(~nationality, nrow=3)+
  labs(y="Age at time of mission", x="Year of mission", title="Space missions and the age of astronauts at take-off")+
  scale_color_brewer(palette = "YlOrRd")+   #package with some nicer color themes
  theme(plot.background = element_rect(fill = "#1d1330", color = "#1d1330"), 
          panel.grid.major.x = element_blank(),
          panel.grid.major.y = element_line(color = "#3c2e54"),
          panel.grid.minor = element_blank(),
          panel.background = element_rect(fill = "#1d1330", color = "#1d1330"),
          text = element_text(color = "white"),
          axis.text = element_text(color = "white"),
          axis.title = element_text(color = "white"),
          axis.ticks = element_blank(),
          legend.background = element_rect(fill = "#1d1330", color = "#1d1330"),
          legend.key = element_rect(fill = "#1d1330", color = "#1d1330"),
          strip.background = element_rect(fill = "#1d1330", color = "#1d1330"),
          strip.text = element_text(color = "#1d1330")
          )+ #change background and text colors. Strip is for facet label items (Setting text to same color of background to hide)
  scale_shape_manual(values = c(16, 15, 17))+ #manually pick what point shapes to use 
  scale_size_continuous(labels = scales::comma)+  #reformat numbers in legend
  guides(color = guide_legend("Mission number", order=1, ncol=2, override.aes = list(size = 3)),
         shape = guide_legend("Nationality", order=3,override.aes = list(size = 3, color="white")),
         size = guide_legend("Mission length/ hr", order=2, override.aes = list(color="white")))  #edit how legend looks; name, order, how many rows/columns to use for each, and overrides of key color and size
 
```


